### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by atd** [P2Pvalue/teem#121]
This might help https://libraries.io/bower/angular-emoji-picker

**Comment by prastut** [comment]
Do we want emoji's in just Chat or everywhere?

**Comment by llopv** [comment]
Right now in the chat, and in the future we can consider extend emoji support to other places.

Other interesting resources:

1. Emoji opensource libraries: [emojione](http://emojione.com/demo/) and [twemoji](https://twitter.github.io/twemoji/2/test/preview.html).
2. Emoji library for angular: [ng-embed](https://github.com/ritz078/ng-embed)

**Comment by prastut** [comment]
@elenamv , @atd I have a UX question. 

* Will the users be willing to type the emoji's out. Like typing `:smile:` will result into :smile:.
* Or the users should be presented with a toolbar that contains all emoji's?

**Comment by llopv** [comment]
Both of them. I've been advancing in this issue these days, and we already have the first feature. I may do the second one in the following days.

**Comment by prastut** [comment]
@llopv I was able to recreate the tying-into-emoji thing using ng-embed and it's seems pretty simple to integrate. Let me know if you want to share some work.

**Comment by llopv** [comment]
I've tried ng-embed, emojione and twemoji, and according to the opinions of our mates, finally I've chosen js-emoji. It allows us to change the emoji style (apple, google, emojione, twemoji...) only by changing a parameter, and it suports all the features I was looking for an emoji library.

It is a pity we have been working in the same feature without knowing what was doing the other. We should have a way to make public what is going on, an who is working on what. Let me discuss it with the team, we may find a solution for this.

**Comment by atd** [comment]
@llopv @prastut you can assign an issue to yourself or put a comment

**Comment by llopv** [comment]
Yes, I can take care of the rest of this issue, making the emoji picker.
