### ISSUE TITLE
Language fallback

### ISSUE THREAD

**Issue by llopv** [P2Pvalue/teem#157]
If main browser language is not available in teem `l10n`, it should fall back to the other `navigator.languages` defined by the user.

If none of them are available, we should use English as last resort.

**Comment by llopv** [comment]
I want to add a note. Language fallback is not failing in https://teem.works for some reason, but it is failing when using `grunt` in a clean installation.

**Comment by atd** [comment]
You mean `gulp`, right?

Could you provide more details? Console error logs, network requests..

**Comment by llopv** [comment]
Yes, `gulp`.

In teem.works doesn't fail because the server doesn't return 404 error when asking for a non-existent language file:

https://app.teem.works/l10n/ca.json

Gulp server at localhost:8000 returns 404, and angular-translate isn't managing it correctly. We have to check its configuration.
