### ISSUE TITLE
Lost editions in pad even with "saved" info shown

### ISSUE THREAD

**Issue by atfornes** [P2Pvalue/teem#164]
Lost of editions where lost even when the "saved" info was appearing after each input in the pad.

**Comment by atd** [comment]
:scream: 

Steps to reproduce?

**Comment by atfornes** [comment]
I do not have steps to reproduce, we just were writing in a pad, for maybe an hour, then have the disconnected alert, reload and lose the content... luckily we copy/pasted the editions

**Comment by pablojan** [comment]
Please, could you provide info about client's platform, internet's
connection type...? Thank you

2016-02-09 16:48 GMT+01:00 atfornes <notifications@github.com>:

**Comment by atfornes** [comment]
It was a Safari 8.0.8 browser with an stable wireless connection.

**Comment by pablojan** [comment]
Movil, Desktop...? dime tb que documento era, de que comunidad/workspace...
voy a buscar cursos de clarividencia!

2016-02-09 17:32 GMT+01:00 atfornes <notifications@github.com>:

**Comment by atfornes** [comment]
Desktop, this [project](https://app.teem.works/#/projects/cHJvdG90eXBlLnAycHZhbHVlLmV1L3MrTkt1YTNSTmxTNkE?tab=pad) , user modifying was `pete` I do not know which other information is useful, please let me know if you think I m miing something else

**Comment by atfornes** [comment]
long time this has not happen... finger crossed
