### ISSUE TITLE
No need to be so accurate in needs progress :D

### ISSUE THREAD

**Issue by pablojan** [P2Pvalue/teem#169]
Wow, this must be consuming a lot of CPU cycles. Please to consider reduce the precision. :joy: 

![captura de pantalla de 2016-03-09 13 45 15](https://cloud.githubusercontent.com/assets/4454927/13635610/3fcea0d6-e5fd-11e5-9a4f-d5ef06432248.png)

**Comment by atd** [comment]
LOLLL  :joy:

**Comment by llopv** [comment]
:scream:
