### ISSUE TITLE
Clear My teems view after logout

### ISSUE THREAD

**Issue by atfornes** [P2Pvalue/teem#172]
On logout when you are watching your teems list, the list is not cleared.

TODO: Either redirect or clear view on logout.

**Comment by amanjain97** [comment]
@atfornes I think the issue is solved so maybe you can close the issue.

**Comment by atd** [comment]
@amanjain97 please take a look at https://help.github.com/articles/closing-issues-via-commit-messages/ on how to close issues from commits (and pull requests)
