### ISSUE TITLE
Two 'sends' are required to login/register/etc on Teems list and Community list views

### ISSUE THREAD

**Issue by atfornes** [P2Pvalue/teem#173]
on Teems list and Community list view, the register/login modal does not disappear until the user has clicked twice the send button or presse twice intro key.

This do not happend in any teem tab view :confused:

**Comment by atd** [comment]
I am also experiencing this in the Teem info view

**Comment by atfornes** [comment]
I am working on this now, it seems relate with the use of SessionService.onload, maybe because it overlaps with the new event system

**Comment by atfornes** [comment]
closed by #6db4712, thanks @atd
