### ISSUE TITLE
Unable to upload avatar image

### ISSUE THREAD

**Issue by atd** [P2Pvalue/teem#175]
POST https://swellrt.teem.works/attachment/zvQHoVNKolA;sid=fmu1qitd0t994bhlujwiisni 500 (An error occurred while upload the file : Not supported yet.)

**Comment by pablojan** [comment]
FYI, I unsuccesfully tried to reproduce this (upload a file via SwellRT's API, using session id tracking with url)

**Comment by atd** [comment]
I uploaded the P2Pvalue semihorizontal logo (png)

**Comment by atd** [comment]
Changing `attachment_store_type = mongodb` to `disk` solves this issue
