### ISSUE TITLE
Problems to login after logout in app version

### ISSUE THREAD

**Issue by drozas** [P2Pvalue/teem#178]
Hello everyone!

I think I have found a bug in the app version. I have one account in which I have already set a password (I did this using the Web version). In my app, I had another testing account. I logout from it without any problems, but when I try to login with the proper account I get a White Screen of Dead with the title set as follows (literally); {'session.'+form.current+'.title' | translate}}
This is happening only in the app version. My Android version is 4.4.2

If there is anything else I can help with in reporting, let me know ;-)

**Comment by drozas** [comment]
Clearing up the data from Android solves this (this might be a clue to help to solve it)

**Comment by atfornes** [comment]
Thanks @drozas!

Can you please let us know the steps you followed to login and from which screen you were trying to login (a teem/ a community view/ a list of communities view)?

**Comment by drozas** [comment]
Awesome! That is a such a quick reply ;-) @atfornes 
I cannot reproduce it [quickly] again, I am afraid, because I cleaned the data, but it was in the list of communities view

**Comment by atfornes** [comment]
was it from the 'Join us' link that appear in the side menu where the user avatar usually appears?

**Comment by drozas** [comment]
Yes, the problem was why using the "Join us" link

**Comment by atd** [comment]
Maybe the old `localStorage.userId` was still over there and caused the issue?

**Comment by atfornes** [comment]
Thanks @drozas, it should be fixed now.

@atd, FYI, it was an issue introduced by https://github.com/P2Pvalue/teem/commit/6e61c28326b4ff6ef13850e115d78bff307c5a89#diff-f564bc14651d7379d71e731a1e79f4e3R75, when the user was `undefined`, the `User.current().nick` was giving the error because it could not read `nick` of `undefined`

**Comment by atd** [comment]
Thank you for the fix @atfornes
