### ISSUE TITLE
notifications stopped working

### ISSUE THREAD

**Issue by atfornes** [P2Pvalue/teem#182]
It seems to be related with new session management and introduction of resume session.

**Comment by atfornes** [comment]
thanks @atd for reporting

**Comment by atfornes** [comment]
@atd, @llopv, what do you think about bringing commits f9cf3e6 and  126a8d4 which fixes notifications to production server?

**Comment by atd** [comment]
I have a comment in 126a8d4

On the other hand, I would continue the work on master

What about adding some specs so notifications are not broken again?

**Comment by atd** [comment]
@atfornes I did not get an answer on the specs part. What do you think?

**Comment by atfornes** [comment]
@atd, sorry, you are right. I had no answer because I was thinking how to do it... It seams like a lot of work to test that the notifications are broken, because we will need to test it on an Android Virtual Device. I do not know if there is a workaround or if we do not need to test that the notifications are actually working, but maybe just check that the device is registered in the notifications after login.

What do you think?

Are we going to need to run other tests in Android Virtual Devices?

**Comment by atd** [comment]
Thank you @atfornes 

Testing in ADVs would be great, but I think we can keep it simple now.

Just extending `test/spec/controllers/session.js` with calls with `cordova=android` in `$location.search` and mocking the cordova notification plugin should be straightforward and enough by now.
