### ISSUE TITLE
Close "upload picture' with Esc

### ISSUE THREAD

**Issue by atd** [P2Pvalue/teem#183]

**Comment by prastut** [comment]
Progress:

* I understood what needs to done and which files to change. Mainly `uploadPictureModal.js` & `upload-picture-modal.html`

Some doubts:

* Using the ng-keyup directive to record the "esc key". Now the keyup event works well for input tags.
How do I attach thee directive to let's say a <div> and record the keypress?
* Also since key-presses are browser things, I tried $scope.$apply too. Didn't work.

Have the following code in place:

`$scope.keyUp = function(event){
          console.log(event);
          console.log('Hello');
            if (event.which === 27) {

              console.log('Hello');
              SharedState.turnOff('uploadPictureSharedState');
              event.preventDefault();

            }
        };
`

**Comment by llopv** [comment]
Interesting. I would write a new directive `closeOnEsc` that encapsulates this functionality. It would be great if it were reusable for any modal/overlay.

**Comment by prastut** [comment]
Hi @llopv,
Thanks for the suggestion. Following is my `closeOnEsc.js` directive's content:

```
'use strict';

angular.module('Teem')
  .directive('closeOnEsc',['$document', function($document) {
    return {
      link: function(scope, element, attrs) {
        console.log('Hello');
        element.on('keyup', function (event){
          console.log('Hello Inside');
        });

        element.on('mousemove', function(event){
          console.log('Mouse moved');
        });
      }
    };
  }]);
   

```

The mousemove element fires and I see mulitple console.logs for the same. But the keyup function doesn't fire at all. Ignore the use of $document, was trying something.

**Comment by llopv** [comment]
I see... `keyup` events are triggered from inputs, textareas... You may need to use a library that is specific to catch hotkeys, such as [angular-hotkeys](https://github.com/chieffancypants/angular-hotkeys).

**Comment by prastut** [comment]
@llopv I agree but I think the library is specific for hotkey combinations. Do we need it at this point of time? Otherwise I have implemented a custom generic directive, which you can review.

**Comment by llopv** [comment]
Awesome, you've got it. I was proposing the library because I it have [an example](https://github.com/chieffancypants/angular-hotkeys#binding-hotkeys-in-directives) to use `keyup` with the esc hotkey and I thought it was tricky, but it wasn't. Good job.

**Comment by atfornes** [comment]
already fixed
