### ISSUE TITLE
Open app.teem.works urls with the app

### ISSUE THREAD

**Issue by atd** [P2Pvalue/teem#191]
If the app is installed, open teem urls in the app

**Comment by atfornes** [comment]
working on this now.

htt1p://www.danhough.com/blog/cordova-android-web-intents/http://www.danhough.com/blog/cordova-android-web-intents/
http://android.stackexchange.com/questions/37549/force-link-to-open-in-app-not-my-default-browser
https://github.com/Initsogar/cordova-webintent
http://stackoverflow.com/questions/28198983/ionic-cordova-add-intent-filter-using-config-xml/28217626#28217626

**Comment by atfornes** [comment]
@atd, c0c570d fixes this issue. To make it work and build the new image android platform has to be removed and added from cordova:
`cordova platform remove android && cordova platform add android`

@atd, Could you please review the changes and deploy or let me know how to deploy?

Thanks :smile:

**Comment by atd** [comment]
LGTM. I can deploy or tell you how, whatever you want

**Comment by atfornes** [comment]
Thanks @atd, whatever is easier for you, if it i quicker to deploy it than to explain it, go ahead, if not, let me know how to do it :smile:

**Comment by atfornes** [comment]
@atd, how is this going?

**Comment by atd** [comment]
@atfornes I am sending you an email with the recipe

**Comment by atfornes** [comment]
Thanks @atd!
