### ISSUE TITLE
Teem icons are not aligned in mobile

### ISSUE THREAD

**Issue by atd** [P2Pvalue/teem#195]
![image](https://cloud.githubusercontent.com/assets/26228/14100318/dd2a3644-f58c-11e5-9749-9f2e92d0027b.png)

**Comment by llopv** [comment]
This is because of teem title takes up 3 lines. We may reduce it to two, as we did with communities titles.

**Comment by atd** [comment]
Sure? I think it has to do with the width, not the height

**Comment by atfornes** [comment]
old project view. Not applicable issue anymore
