### ISSUE TITLE
Menu shows a green line 

### ISSUE THREAD

**Issue by atd** [P2Pvalue/teem#201]
![image](https://cloud.githubusercontent.com/assets/26228/14100702/ade9890e-f58f-11e5-82b8-769fc19e8a99.png)

**Comment by elenamv** [comment]
We need to change that because its a very confused press mode

**Comment by atd** [comment]
@elenamv we would need a hint on how to show the menu items when you are in the section you clicked

**Comment by atd** [comment]
Ops, you are meaning the desktop view?

**Comment by elenamv** [comment]
Sure! i´m working on that
The mobile view has the line too, when you "tap" the menu option
