### ISSUE TITLE
Increase pad height

### ISSUE THREAD

**Issue by atd** [P2Pvalue/teem#204]
In Teem info tab, the pad only shows one line. It should expand to the remaining space in the screen, or at least 3 lines?

**Comment by elenamv** [comment]
Yes, in the designs we have more, but better 3 lines to show the info before expand
You mean this?

![captura de pantalla 2016-03-29 a las 9 40 19](https://cloud.githubusercontent.com/assets/16928147/14101092/541d07ea-f592-11e5-9d85-0ff8d35aab85.png)

**Comment by atd** [comment]
This one:

![image](https://cloud.githubusercontent.com/assets/26228/14101581/b55c517a-f595-11e5-898d-e08cef5abe53.png)

**Comment by atfornes** [comment]
Issue for old design
