### ISSUE TITLE
Decrease new need placeholder font

### ISSUE THREAD

**Issue by atd** [P2Pvalue/teem#206]
![image](https://cloud.githubusercontent.com/assets/26228/14101121/82704c60-f592-11e5-8b50-a7cdd713b24b.png)

**Comment by amanjain97** [comment]
@atd  I need to confirm the size . Right now , it is 1.21em and I have changed to 1.14em. Is that good or some other change is required

**Comment by atd** [comment]
@elenamv can you please provide @amanjain97 with more info?

**Comment by elenamv** [comment]
It must be 16 px.

**Comment by elenamv** [comment]
@amanjain97 maybe you have to change this a 14px (0.875 em), but we need to see you can read it correctly.
You can eliminate the icon and put the text in #00bfa0. When you "tap", appears the icon

Look on the designs:
![captura de pantalla 2016-04-04 a las 10 28 49](https://cloud.githubusercontent.com/assets/16928147/14242185/38d98496-fa50-11e5-83a9-a24424df79a9.png)
![captura de pantalla 2016-04-04 a las 10 24 49](https://cloud.githubusercontent.com/assets/16928147/14242196/43c9d932-fa50-11e5-8d60-fc642b910469.png)

Could you prove it?

**Comment by amanjain97** [comment]
@elenamv I have made changes in needs comment placeholder and new need placeholder 
Initially it was this.
![git2](https://cloud.githubusercontent.com/assets/11582770/14350223/b342dc04-fce5-11e5-8acb-f972d69a907a.png)
now it looks like this 
![git3](https://cloud.githubusercontent.com/assets/11582770/14350291/2ee697f6-fce6-11e5-8208-37edbad99e03.png)

Please tell if any other change is required.

**Comment by amanjain97** [comment]
@atd @elenamv please tell if the above work was good or something else is to be done regarding the issue

**Comment by atd** [comment]
@elenamv what do you think?

**Comment by elenamv** [comment]
@amanjain97 @atd is perfect! thanks
To be even better, could you focus compared to other elements? and the "new need button" with this style, please

![2ee697f6-fce6-11e5-8208-37edbad99e03](https://cloud.githubusercontent.com/assets/16928147/14553393/985e2734-02e6-11e6-8c6d-d9310b27ea15.jpg)
