### ISSUE TITLE
chat write text box

### ISSUE THREAD

**Issue by elenamv** [P2Pvalue/teem#218]
Could we fix this?

![img_20160404_101449](https://cloud.githubusercontent.com/assets/16928147/14242556/60741272-fa51-11e5-9993-fb0fcddec597.png)

![captura de pantalla 2016-04-04 a las 10 38 06](https://cloud.githubusercontent.com/assets/16928147/14242569/686666c4-fa51-11e5-9b20-84de5b3ee1ad.png)

**Comment by atd** [comment]
@elenamv should we remove the bottom line? What is the font size?

**Comment by elenamv** [comment]
Yes, we can remove it
The font size is 16 px
