### ISSUE TITLE
Remove @domain from password recovery emails

### ISSUE THREAD

**Issue by atd** [P2Pvalue/teem#219]
> Restore atd@prototype.p2pvalue.eu password

Users don't know what the hell prototype.p2pvalue.eu is

**Comment by atd** [comment]
This should be solved with the password recovery email template @atfornes ?

**Comment by atfornes** [comment]
This commit in SwellRT fixes solves the problem https://github.com/P2Pvalue/swellrt/commit/7dad683c5309564eaa8d9f3a1757202310e019f6, it is still not merged. @atd, @pablojan, o you think it is worth it to merge it or we can wait for the next changes?

**Comment by atd** [comment]
Can we close this @atfornes ?

**Comment by atfornes** [comment]
@pablojan, I cannot see this commit in master P2Pvalue/swellrt@7dad683, can you please add it and confirm that other commits are not lost with the last changes in Swell?

Thanks!
