### ISSUE TITLE
Fix share dialog tile style

### ISSUE THREAD

**Issue by atfornes** [P2Pvalue/teem#220]
![captura de pantalla de 2016-04-04 12 10 50](https://cloud.githubusercontent.com/assets/7475584/14246343/7a523298-fa5e-11e5-8ccc-4a7533beaafe.png)

**Comment by atd** [comment]
Duplicate of #198

**Comment by atfornes** [comment]
Ups, Sorry :S

**Comment by atd** [comment]
No problem, we have many issues :sweat_smile:
