### ISSUE TITLE
floating button shadow

### ISSUE THREAD

**Issue by elenamv** [P2Pvalue/teem#226]
This shadow works over light background, but when the background is dark, you see the shadow lighter

![img_20160406_094719](https://cloud.githubusercontent.com/assets/16928147/14309438/bd1f5dec-fbdc-11e5-9b05-c5719b5085ea.jpg)

**Comment by atd** [comment]
We have to test how the new material design library works with this

**Comment by atd** [comment]
Closed via https://github.com/P2Pvalue/teem/commit/4027b9376777ed834732d47e106ceacbce0f7f0e
