### ISSUE TITLE
Menu - swipe left gesture

### ISSUE THREAD

**Issue by elenamv** [P2Pvalue/teem#231]
When the menu is open, give users the possibility of being able to close with this gesture

**Comment by atd** [comment]
This is an issue for mobile angular ui ;-)

**Comment by llopv** [comment]
@atd We are not using [mobile-angular-ui.gestures](http://mobileangularui.com/docs/module:mobile-angular-ui.gestures/). We are using hammerjs instead, so we may apply that directives by ourselves.
