### ISSUE TITLE
Teem links don't open in android app

### ISSUE THREAD

**Issue by llopv** [P2Pvalue/teem#237]
They redirect me to /home/teems (My Teems).

**Comment by atd** [comment]
We need an intent handler

https://www.npmjs.com/package/cordova-plugin-intent

**Comment by atfornes** [comment]
@atd, FYI we already have an intent handler, see c0c570d

I believe that we have some redirections in the code that change the expected behavior. Maybe the intent handler is not working correctly, but when I tested, it worked.

**Comment by atd** [comment]
@atfornes I already checked that commit

Please take a look at https://www.npmjs.com/package/cordova-plugin-intent#usage

**Comment by atd** [comment]
The url is passed inside the intent. We have to handle the intent. If we just open the app, it will just redirect to /

**Comment by atfornes** [comment]
ok, got it ;) thanks @atd.
