### ISSUE TITLE
Send chat icon color lost (Material design)

### ISSUE THREAD

**Issue by atfornes** [P2Pvalue/teem#240]
After sending a message from my Samsung Galaxy S3 with android 5.1.1 the color of the send icon is lost after some "noisy glitches"

In the picture it can be seen that the ionis no longer green but gray:
![screenshot_2016-04-15-19-29-16](https://cloud.githubusercontent.com/assets/7475584/14571547/b416de98-0341-11e6-96c6-74de99040b57.png)

This issue appeared after including material design. @atd, check this issue :+1:

**Comment by atd** [comment]
http://stackoverflow.com/questions/17233804/how-to-prevent-sticky-hover-effects-for-buttons-on-touch-devices

**Comment by atd** [comment]
And more:

http://stackoverflow.com/questions/8291517/disable-hover-effects-on-mobile-browsers
