### ISSUE TITLE
Weird shadow at menu item after selection

### ISSUE THREAD

**Issue by atfornes** [P2Pvalue/teem#244]
When selecting the option that is already selected in the menu, a weird shadow appears over the menu item.

![screenshot_20160418-085615](https://cloud.githubusercontent.com/assets/7475584/14601956/0b030462-055d-11e6-8453-07f9e0356714.png)

Related with #211

**Comment by atfornes** [comment]
Wow, that was quick @atd ;)

**Comment by atd** [comment]
I am afraid you were quicker! I was finishing to discuss it with @elenamv when you opened the issue :grin:
