### ISSUE TITLE
Automatically does not remove from communities teems, if member leaves the community

### ISSUE THREAD

**Issue by prastut** [P2Pvalue/teem#247]
I have a community named "Test". In it I have a Teem named "Setup".

Initially this community had 2 members and the Teem "Setup" had the same 2 members.  Now 1 member has left the community as you can. But the "Setup" teem still has 2 members in it.  
![fireshot capture 36 - teem - http___localhost_8000_ _communities_bg9jywwubmv0l3mryvgzte02ouzyske](https://cloud.githubusercontent.com/assets/10279686/14780634/6bc27c1c-0afb-11e6-8711-f16e33a26887.png)

The teem "Setup" still has 2 members:
![fireshot capture 37 - teem - http___localhost_8000_ _teems_bg9jywwubmv0l3mryvgzte02ouzysko_tab pad](https://cloud.githubusercontent.com/assets/10279686/14780687/c1abdb32-0afb-11e6-89c2-23089d0c7812.png)

**Comment by atd** [comment]
We need a dialog for asking the user if she wants that

**Comment by atfornes** [comment]
I believe this is working now. :)
