### ISSUE TITLE
Buggy menu-session-counters

### ISSUE THREAD

**Issue by prastut** [P2Pvalue/teem#249]
Two bugs I could find:

* Whenever you type a new message and press enter in chat, the total teem display in menu-session-counters increases by 1
* Whenever you create a community yourself, the total community counter doesn't change. The page needs to refreshed to get the current count for the same. Found this bug by doing the following. The person is a new user and is part of 0 communities:
  * Create a community yourself. The counter doesn't increment.
  * Now leave the community. The counter shows -1.

**Comment by atd** [comment]
LOL

**Comment by prastut** [comment]
@atd is this a bug at your end too?

**Comment by atd** [comment]
Of course! Good catch!

**Comment by atd** [comment]
@prastut it is better to open an issue for each
