### ISSUE TITLE
hide tabs when editing chat/pad/needs 

### ISSUE THREAD

**Issue by atfornes** [P2Pvalue/teem#250]
![captura de pantalla de 2016-04-26 11 52 43](https://cloud.githubusercontent.com/assets/7475584/14815814/70081142-0ba5-11e6-9aa3-f20e35b9e894.png)

https://projects.invisionapp.com/d/#/console/6489701/152960213/comments/61161155

**Comment by llopv** [comment]
Fixed with https://github.com/P2Pvalue/teem/commit/f9dc5d0e8571a1afec40a428b4a92ef730ed5152

**Comment by atfornes** [comment]
thanks @llopv, In desktop this feature is a bit misleading and I would not activate it... I wanted to switch to pad tab but could not find the tab, I unfocused the caht because I am aware of this "feature".

Should we open a new issue? reopen this one?

**Comment by llopv** [comment]
Ok, let's reopen it.
