### ISSUE TITLE
Language changed to Spanish

### ISSUE THREAD

**Issue by prastut** [P2Pvalue/teem#252]
Recently updated my fork so that it is leveled up with upstream. When I reloaded Teem, the language has changed to French. 

I deleted cookies still no luck.

**Comment by atfornes** [comment]
Thanks for noticing @prastut, I guess it is Spanish.

:cry: This bug would be really cool: a new translation added, unfortunatelly I think it is not the case.

**Comment by prastut** [comment]
Yup it's spanish. Any tips on how to solve this bug?

**Comment by atfornes** [comment]
I have no Idea which commit could have changed this. 

If there are not a lot of commits from your last working version and the failing one, you can try to guess which commit introduces the bug by its commit message.

 you can also do a git bisect from a working version to detect it: https://git-scm.com/docs/git-bisect

maybe @atd or @llopv remember changes they did that could introduce the issue.

Good luck with the search ;)

**Comment by llopv** [comment]
Sorry, it was my fault.
