### ISSUE TITLE
For screen width 1150*968 - 1200*968, position of buttons and icons are not proper. 

### ISSUE THREAD

**Issue by prastut** [P2Pvalue/teem#257]
Observed on a 17' laptop. Screenshots:
![fireshot capture 40 - teem - http___localhost_8000_ _communities](https://cloud.githubusercontent.com/assets/10279686/14927884/3550c8bc-0e72-11e6-90a2-057c1dc64562.png)

![fireshot capture 42 - teem - http___localhost_8000_ _home_communities](https://cloud.githubusercontent.com/assets/10279686/14927904/53db839e-0e72-11e6-838c-7e3b0bed35ac.png)

**Comment by llopv** [comment]
@elenamv What should we do? Replace _Join this community_ message by just _Join_?

**Comment by elenamv** [comment]
@llopv In the redesign we have removed the button to the landing page and leave it only in the detail of the community
https://projects.invisionapp.com/d/main#/console/6489701/139322506/preview#project_console
