### ISSUE TITLE
Throw err

### ISSUE THREAD

**Issue by amitojsingh** [P2Pvalue/teem#263]
I have successfully installed teem in my system by the steps written in README.md. 
When I run the application by writing 

> Gulp

it gives error

> module.js:340
>     throw err;
>     ^
> Error: Cannot find module 'pinkie-promise'
>     at Function.Module._resolveFilename (module.js:338:15)
>     at Function.Module._load (module.js:280:25)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> (/home/sifat/teem/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-wrapper/node_modules/download/node_modules/request/node_modules/har-validator/lib/index.js:3:15)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> (/home/sifat/teem/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-wrapper/node_modules/download/node_modules/request/lib/har.js:5:16)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)

How can I resolve it?
Thanks in advance.

**Comment by atfornes** [comment]
Hello @amitojsingh,

This seems to be a problem with a missing dependency. Can you please confirm that you have run `npm install`?

An alternative way of starting Teem that take care of missing dependencies is `npm start`, please run that instead of `gulp` and let us know if you keep having problems.

**Comment by amitojsingh** [comment]
Sorry for the late reply 
I used
> npm start 

But I am stil getting this <a href="https://gitlab.com/snippets/19506"> Error</a>.

**Comment by atfornes** [comment]
can you please confirm that you have the required versions of *node* (v4.2.x) and *docker* (v1.9.x) as explained in README.md?

**Comment by atfornes** [comment]
You can also try to reinstall node dependencies, it seems that something is missing but node thinks it is already downloaded:

```bash
# Remove node_modules
rm -fr node_modules

# Reinstall packages
npm i
```

**Comment by atd** [comment]
@amitojsingh I updated that module. Please `git pull` and try again

**Comment by amitojsingh** [comment]
I have solved the above error by using 
> npm install --save module_name 
ie 
npm install --save pinkie-promise

But now I am getting another <a href ="https://gitlab.com/snippets/19510"> Error</a>.
my node version is 4.2.6 
and 
Docker Version is 1.9.1 
Also I have updated the repository of Teem using git pull.

**Comment by atd** [comment]
@amitojsingh try setting `config.minifyImages = false` in your `config.js`

**Comment by amitojsingh** [comment]
@atd Thanks, This worked for me but it gives warning like this 

> WARN: Couldn't figure out mapping for ?:96732,21 → 30,35207 

Also on browser i am getting this!
![screenshot from 2016-05-18 23 20 12](https://cloud.githubusercontent.com/assets/3595397/15369226/572b4458-1d4f-11e6-8e2f-f435a7cbc296.png)
Had I miss something?

**Comment by atd** [comment]
It seems you got a javascript error. Could you open the console and tell us what you have?

**Comment by atfornes** [comment]
This usually happens when https://github.com/P2Pvalue/swellrt (Our backend) is not available. You can confirm this if you see `SwellRT is not defined` error in the browser console. Please, tell us what `docker ps` says about your docker processes and how your `config.js` file looks like (have you changed something?).

Thanks

**Comment by amitojsingh** [comment]
@atd 
here's <a href ="https://gitlab.com/snippets/19887"> Console</a>
@atfornes No, I haven't changed anything

**Comment by llopv** [comment]
You are in the good way, but the default config is very heavy for your computer. Do:

```sh
cp config.js.sample config.js
```
And then `gulp` again. It should go faster. The script finishes when the message `Finished 'default' after ## s` appears:

![console](https://cloud.githubusercontent.com/assets/16879027/15551994/ce442cee-22b8-11e6-9204-618207ddd5fc.png)

**Comment by amitojsingh** [comment]
Thanks @llopv  and everyone for your time it works. 
Also I want to know, Why I have faced so much difficulty in installing? Is their any need to update our README file?
Also, I have seen a issue to Update Readme file.

**Comment by atd** [comment]
@amitojsingh we are interested in a pull request that improves the README file with your expericence

**Comment by atd** [comment]
Please reopen if there are further issues
