### ISSUE TITLE
Buggy behaviour when removing chars after a need integrated in a pad

### ISSUE THREAD

**Issue by atfornes** [P2Pvalue/teem#265]
Removing characters (with backspace or supr key) in the line that follows an integrated need result in buggy behavior:

- the character is not removed as expected
- a red square like the one in following image blinks:

![captura de pantalla de 2016-05-16 12 51 36](https://cloud.githubusercontent.com/assets/7475584/15287817/d64856f4-1b65-11e6-85bf-bf63701a23f6.png)

**Comment by pablojan** [comment]
Please, provide browser's brand, version and platform

2016-05-16 12:58 GMT+02:00 atfornes <notifications@github.com>:

**Comment by atfornes** [comment]
Firefox 46.0.1, but with @atd, @llopv we have seen similar behavior with an android browser.

**Comment by atd** [comment]
Cannot reproduce it :confounded: 

More details appreciated

**Comment by atfornes** [comment]
Cannot reproduce again, maybe it was fixed by previous work on integrated needs, congrats!

I will close and reopen if detected again.
