### ISSUE TITLE
Review notifications

### ISSUE THREAD

**Issue by llopv** [P2Pvalue/teem#272]
Some users doesn't receive them. Maybe it is after an app update. Maybe we have to register notifications when the app updates.

**Comment by atd** [comment]
Guys, are we taking this into account?

![image](https://cloud.githubusercontent.com/assets/26228/16052602/3eaeaa0c-3265-11e6-84d6-d6e93925c72c.png)

**Comment by atfornes** [comment]
I think PushNotification.init() is only called in login callback.

Can we find a way of calling it when the app starts and only if we are logged in?
