### ISSUE TITLE
Huge margin in pad needs

### ISSUE THREAD

**Issue by atd** [P2Pvalue/teem#273]
Last commits have introduced a huge margin in pad needs

![image](https://cloud.githubusercontent.com/assets/26228/16075989/8f7752b8-32f1-11e6-8562-4b19d86bfdfc.png)

**Comment by atd** [comment]
It seems to happen in the new version of chrome only (51.0.2704.79)

Can anybody confirm with other chrome versions?

**Comment by elenamv** [comment]
Yes, its happens to me too
![captura de pantalla 2016-06-15 a las 13 54 42](https://cloud.githubusercontent.com/assets/16928147/16078772/f057310c-3300-11e6-8465-0917751d3767.png)

**Comment by atfornes** [comment]
@atd, I show the issue in chromium 51.0.2704.63. I was sure that I had reported the issue, but I can not find it now...

**Comment by atd** [comment]
@atfornes do you mean this one? https://github.com/P2Pvalue/teem/issues/264

I think it was a different one

**Comment by atfornes** [comment]
@atd, no, I mean other issue of this specific problem with chrome/chromium. It was not introduced by the newest changes, it have been around at least for one week.

**Comment by atd** [comment]
It is caused by SwellRT `-webkit-user-modify: read-write-plaintext-only;` style attributes introduced in `sw-widgets`

Removing them solves the issue

**Comment by atfornes** [comment]
fixed in P2Pvalue/swellrt#154
