### ISSUE TITLE
overlay modals title hiden

### ISSUE THREAD

**Issue by atfornes** [P2Pvalue/teem#274]
the login modal (and probably other overlay modals) have their title hidden (it is upper than the upper limit)

![captura de pantalla de 2016-06-15 12 11 36](https://cloud.githubusercontent.com/assets/7475584/16076241/9f7d1ef8-32f2-11e6-9c87-b4fb9c45c7c5.png)

**Comment by llopv** [comment]
Fixed by 6ff3e750232501c127465c01424f811ce17e0ef5.
