### ISSUE TITLE
PAD text format

### ISSUE THREAD

**Issue by elenamv** [P2Pvalue/teem#280]
Sometimes, it don´t save the text formatting (bold, headed...)

**Comment by atd** [comment]
@elenamv if you can add more details it helps us to debug. For example: "when I do this and this.. then I cannot use the bold button"

**Comment by elenamv** [comment]
When I select a text to make it bold, the toolbar disappears, but not always...)

**Comment by atfornes** [comment]
@elenamv, I believe it is fixed now, if not, can you open it again the issue?
