### ISSUE TITLE
Teem image spinner

### ISSUE THREAD

**Issue by elenamv** [P2Pvalue/teem#281]
Place a spinner in the picture because it seems that you have uploaded and has not been saved...

...in the following picture types:
- [ ] ~~Chat pictures~~
- [ ] Pad pictures
- [ ] User, community and project pictures

**Comment by llopv** [comment]
In witch pictures? In all of them, I figure out.

**Comment by elenamv** [comment]
Yesss
We have to provide always to users information about what is happening ;)
