### ISSUE TITLE
toolbar pad disappears

### ISSUE THREAD

**Issue by elenamv** [P2Pvalue/teem#282]
Sometimes, you selec something of the toolbar, and it disappears and the doc leaps up

**Comment by atd** [comment]
I cannot reproduce it @elenamv 

Please, could you provide with more detailed instructions so we can see it in our computers and investigate what it is going on?

**Comment by elenamv** [comment]
These screenshots serves to illustrate the problem?
![captura de pantalla 2016-06-23 a las 9 05 10](https://cloud.githubusercontent.com/assets/16928147/16294611/d1bdee80-3921-11e6-853c-286d7894ef4b.png)
![captura de pantalla 2016-06-23 a las 9 05 19](https://cloud.githubusercontent.com/assets/16928147/16294612/d1ea22b6-3921-11e6-8c90-3019b93a1544.png)

**Comment by atd** [comment]
They help but still I miss some steps to reproduce it. Like:

1. Click on the pad
2. Select one sentence
3. ...

**Comment by atd** [comment]
@llopv maybe this is related with the change of focus to click events

**Comment by llopv** [comment]
Yes, this is because she releases the mouse outside the editor and this triggers an outer-click that hides the toolbar.

We should be able to detect these false clicks looking at the `$event` triggered by outer-click.

**Comment by llopv** [comment]
Anyway this only happens in desktop environments (where you can do drag and drop), and we are going to change the pad view. The new pad view does not rely on clicks and outer-clicks to show and hide the toolbar, so I think it is useless to solve it.

**Comment by llopv** [comment]
The new desktop view is in master, so this behaviour is not an issue any more.
