### ISSUE TITLE
Empty pad after navigating back to an open project in desktop view

### ISSUE THREAD

**Issue by atfornes** [P2Pvalue/teem#289]
After navigating from Teem1 to Teem2 through left column teem navigation and going backthrough that navigation to Teem1, the pad appears **empty**

**Comment by atfornes** [comment]
Thanks @atd, but it is still failing for me.

**Comment by atd** [comment]
Are you aware that tests are broken and it is still not deployed in production?

**Comment by atfornes** [comment]
It seems to work now
