### ISSUE TITLE
Pad saving spinner not working

### ISSUE THREAD

**Issue by atd** [P2Pvalue/teem#292]
See https://github.com/P2Pvalue/swellrt/issues/167

**Comment by atfornes** [comment]
@atd, I think it is an old issue and that now it is working. Am I right? can we close it?

**Comment by atd** [comment]
It is currently working, but I am missing it in desktop (I was missing it yesterday when we were working on Teem metrics)

I've opened a new issue https://github.com/P2Pvalue/teem/issues/337
