### ISSUE TITLE
create need from pad broken

### ISSUE THREAD

**Issue by atfornes** [P2Pvalue/teem#295]
When creating a new need from pad, it appears to have been deleted:

![captura de pantalla de 2016-07-15 10 33 22](https://cloud.githubusercontent.com/assets/7475584/16868410/bfac6610-4a77-11e6-8e6b-3f5e2d0dee45.png)

**Comment by atd** [comment]
@atfornes this commit https://github.com/P2Pvalue/angular-swellrt/commit/9e6660cfb6c39c0e52b163beccf6e48077db2805 clashes with the way need._id has been stored https://github.com/P2Pvalue/teem/blob/master/src/js/services/projectsService.js#L301
