### ISSUE TITLE
Responsive resize

### ISSUE THREAD

**Issue by elenamv** [P2Pvalue/teem#297]
When i make smaller my browser, the screen changes to mobile view but empty. When i resize it again, and make it bigger, the screen it´s still empty. I can´t refresh the section with the header menu, so i have to refresh the browser and lost my user id

![captura de pantalla 2016-08-01 a las 16 57 02](https://cloud.githubusercontent.com/assets/16928147/17298674/3ebed51e-580b-11e6-84af-0473357815a0.png)

**Comment by atfornes** [comment]
responsive resize seams to be working now
