### ISSUE TITLE
Open your profile in a new tab loses the session

### ISSUE THREAD

**Issue by elenamv** [P2Pvalue/teem#298]
When I open my profile in a new tab, my user is lost

![captura de pantalla 2016-08-02 a las 9 12 36](https://cloud.githubusercontent.com/assets/16928147/17320013/a745caa8-5891-11e6-8215-e6d4f6dccf03.png)

**Comment by atd** [comment]
I cannot reproduce it neither in firefox or chrome

Steps:

* Login to teem
* Click on my face, top-right on the screen. Dropdown appears. Right click on "Your profile", open in new tab
* I am still logged in

**Comment by elenamv** [comment]
Ops... i´m using chrome, and i´m not still login...

**Comment by atd** [comment]
Could you post the chrome and operating system version?

**Comment by atfornes** [comment]
Can't reproduce
