### ISSUE TITLE
UI Bugs

### ISSUE THREAD

**Issue by prastut** [P2Pvalue/teem#299]
Following are some UI bugs I noticed:

* The background becomes white and the communities item loses it's border-shadow, giving this effect, on small screen sizes:

![fireshot capture 84 - teem - https___app teem works_communities](https://cloud.githubusercontent.com/assets/10279686/17528511/6352c25e-5e8d-11e6-88f8-735d77538752.png) 

* The caption of community item has no padding and get's stretched to the very end. @elenamv can you confirm that this is not intentional by design, but actually a bug in it's implementation?

![fireshot capture 86 - teem - https___app teem works_communities](https://cloud.githubusercontent.com/assets/10279686/17528579/98064bf6-5e8d-11e6-90f0-40986318f12f.png)

**Comment by llopv** [comment]
I restricted the first caption style for xs screens (mobiles) only, and added padding to community boxes footer.
