### ISSUE TITLE
Links hover

### ISSUE THREAD

**Issue by elenamv** [P2Pvalue/teem#304]
Put on violet, please @llopv 💋 

![captura de pantalla 2016-08-23 a las 19 17 34](https://cloud.githubusercontent.com/assets/16928147/17902152/6a596894-6966-11e6-909b-8917f4a34f9b.png)

**Comment by llopv** [comment]
Violet was very ugly, I just removed the underline.

**Comment by elenamv** [comment]
Ugly or beauty aren´t reasons (baby :)). We need to inform users that those are links, and the best way is changing color while you pass over
