### ISSUE TITLE
Multiple accounts with the same one email address

### ISSUE THREAD

**Issue by fantalavapies** [P2Pvalue/teem#322]
In the registration process is allowed:

nombre+1@blablabla.com
nombre+2@blablabla.com
nombre+hola@blablabla.com
...

Maybe that could be a problem.
Kind regards.

**Comment by atd** [comment]
Thank you @fantalavapies ! This is in fact a p2pvalue/swellrt issue. I have opened it there (referenced above)

**Comment by atfornes** [comment]
Since it is already added to SwellRT issue tracker, should we close it here @atd?

**Comment by atd** [comment]
Yep, I think we cannot do much here, besides giving a helping hand to @pablojan
