### ISSUE TITLE
Email invites are not sent

### ISSUE THREAD

**Issue by atfornes** [P2Pvalue/teem#342]

**Comment by atfornes** [comment]
They are working now... I do not know what happened

**Comment by atd** [comment]
We have some users without an email in production. Maybe was related?

**Comment by atfornes** [comment]
@atd, the issue is for inviting users by introducing their email in the invite selector.

Maybe @llopv fixes for that selector fixed the issue

**Comment by atd** [comment]
Oh ok, thanks for the clarification!
