### ISSUE TITLE
Project needs in rich text editor

### ISSUE THREAD

**Issue by atfornes** [P2Pvalue/teem#39]
Handle project needs inside SwellRT rich text editor. Use style of annotated text provided by SwellRT

**Comment by Akronix** [comment]
what about using markdown or Wiki markup to allow the user still writing on plain text?

**Comment by atfornes** [comment]
@Akronix, we do have rich text editor in pad, try Ctrl+B for write bold text.

This issue is to include need list ad widget of the editor... we are thinking in being able to mark some text in the pad as need and then being able to mark it as resolve, or do other "need" operations from there.

**Comment by atd** [comment]
I opened a new issue about rich text toolbar:

https://github.com/P2Pvalue/pear2pear/issues/83
