### ISSUE TITLE
stats.p2pvalue.eu is taking too much time on app load

### ISSUE THREAD

**Issue by pablojan** [P2Pvalue/teem#70]
![captura de pantalla de 2015-09-23 11 06 36](https://cloud.githubusercontent.com/assets/4454927/10041252/34b19404-61e3-11e5-9db6-828a83b0979b.png)

**Comment by atd** [comment]
See https://github.com/angulartics/angulartics/issues/412

**Comment by atd** [comment]
Moving the server aliviated the issue. However, the ideal would be that it was asynchronous
