### ISSUE TITLE
Problems with @ in text editor (at least in chrome)

### ISSUE THREAD

**Issue by Colosu** [P2Pvalue/teem#73]
When writing in the info section, write an @ at the end of the line generates that the @ and the previous character split from the main text and can't write over they.

**Comment by atfornes** [comment]
Thanks @Colosu, It is probably an editor issue related with https://github.com/P2Pvalue/swellrt/issues/64.

@pablojan, should we reopen that issue or create a new one in SwellRT?

**Comment by atd** [comment]
@Colosu could you please check if this is still happening?

**Comment by Colosu** [comment]
No, sorry, but it's still happening...

2015-11-11 9:17 GMT+01:00 Antonio Tapiador <notifications@github.com>:

**Comment by atd** [comment]
@Colosu could you please tell us what OS and browser you are using?

**Comment by Colosu** [comment]
It happens with chrome in windows 10. With Firefox in Ubuntu it doesn't
happen.

**Comment by atfornes** [comment]
@pablojan, I believe this is fixed now in SwellRT, right?
