### ISSUE TITLE
Have some kind of notification system

### ISSUE THREAD

**Issue by juanjeakabob** [P2Pvalue/teem#79]
It would be great if pear2pear notified us when a change is been made on something we have written before, or in a group we are, etc.....

**Comment by atd** [comment]
Of course @juanjeakabob ! This is our first priority now. @pablojan and @atfornes are working on the notification system.

**Comment by pablojan** [comment]
Examples of notification events:

[User not in a workspace yet]
- "You have been added to a workspace"

[User already in a workspace]
- "There are 2 new messages in workspace W"
- "There are new changes in the pad in workspace W"
- "A new need has been added in the workspace W"
- "The need "N" has been marked as resolved in workspace W" 
- "There are new comments in the need X, in workspace W" (Only if user has commented the need before)

**Comment by atd** [comment]
This is already working in production
