### ISSUE TITLE
Have a rewards / badget / karma / score system

### ISSUE THREAD

**Issue by Akronix** [P2Pvalue/teem#82]
Hello.

It'd be much more encouraging for people If they had a rewards system.
This system should give points or badget to community members when they complete a task. Tasks or needs should be set up with an specific points reward and they could be one-time task, many-times task or unlimited task.

I can give you some examples / use cases if you want to.

**Comment by atd** [comment]
Thank you @Akronix 

A rewarding mechanism is something we will definitely explore during the project.

**Comment by atd** [comment]
This is now tracked as a user story in Taiga

https://tree.taiga.io/project/atd-p2pvalue/us/74
