### ISSUE TITLE
Reorder needs

### ISSUE THREAD

**Issue by Akronix** [P2Pvalue/teem#94]
It'd be interesting if you could change the order of the needs on the needs list.

**Comment by atfornes** [comment]
Thanks @Akronix for your comments on the app :smile:

Currently we have two ideas about how to do it:
  - Let people drag and drop them
  - Let people vote up a need, so popular needs are displayed upper

What do you think about it? do you have other ideas?

**Comment by Akronix** [comment]
what about a half-way approach? let users reorder using drag and drop between needs with same votes.

**Comment by atd** [comment]
Better than focusing in the technical solution, I would try to understand the user need. 

@Akronix, may we have an example on why did you request the feature?

**Comment by Akronix** [comment]
Sure.

I was redacting the needs list with needs as they were coming up to me. Then I wanted to prioritize somehow the most urgent ones from the least ones, so I thought about reordering them by urgency / importance.

**Comment by atd** [comment]
Thank you for the clarification @Akronix. Please, could you give us the details on why they are urgent to you?  An example would help. If you don't want to reveal sensitive information, you can change details as far as they still make sense to you 

It is very important for us to fully understand the problem. This way we can implement an innovative solution that addresses the root of the issue 

Thank you

**Comment by atd** [comment]
Cuarto Propio also rises this issue. There are too many needs and they ask for a better way of visualize them. Some categories emerge: contact with people, discussing issues, investigating other things...

**Comment by atd** [comment]
Moved to https://tree.taiga.io/project/atd-p2pvalue/us/115
